---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-eks
metadata:
  name: hdfs-operator-integration-tests
  description: "Cluster for HDFS Operator Integration Tests (AWS EKS)"
publicKeys: []
spec:
  region: "eu-central-1"
  awsInstanceType: "t2.medium"
  versions:
    _-operator: NIGHTLY
    hdfs-operator: "$HDFS_OPERATOR_VERSION"
  node_count: 3
