= Stackable Operator for Apache HDFS

The Stackable Operator for https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HdfsUserGuide.html[Apache HDFS] is used to set up HFDS in high-availability mode. It depends on the xref:zookeeper:ROOT:index.adoc[] to operate a ZooKeeper cluster to coordinate the active and standby name nodes.

NOTE: This operator only works with images from the https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable%2Fhadoop[Stackable] repository

== Roles

Three xref:home:concepts:roles-and-role-groups.adoc[roles] of the HDFS cluster are implemented:

* Data Node - responsible for storing the actual data.
* Journal Node - responsible for keeping track of HDFS blocks and used to perform failovers in case the active name node fails. For details see: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithQJM.html
* Name Node - responsible for keeping track of HDFS blocks and providing access to the data.

== Kubernetes objects

The operator creates the following K8S objects per role group defined in the custom resource.

* Service - ClusterIP used for intra-cluster communication.
* ConfigMap - HDFS configuration files like `core-site.xml`, `hdfs-site.xml` and `log4j.properties` are defined here and mounted in the pods.
* StatefulSet - where the replica count, volume mounts and more for each role group is defined.

In addition, a `NodePort` service is created for each pod labeled with `hdfs.stackable.tech/pod-service=true` that exposes all container ports to the outside world (from the perspective of K8S).

== Supported Versions

The Stackable Operator for Apache HDFS currently supports the following versions of HDFS:

include::partial$supported-versions.adoc[]

== Docker image

[source]
----
docker pull docker.stackable.tech/stackable/hadoop:<version>
----
