apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: simple
spec:
  version: 3.2.2
  zookeeperConfigMapName: simple-zk
  nameNodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 2
        config:
          dfsNamenodeNameDir: /stackable/hadoop/namenode/data
          ipcAddress:
            port: 9000
          httpAddress:
            port: 60001
          metricsPort: 50000
  dataNodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          dfsDatanodeNameDir: /stackable/hadoop/datannode/data
          httpAddress:
            port: 60002
          metricsPort: 51000
  journalNodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          httpAddress:
            port: 60003
          metricsPort: 51000




