apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: simple
spec:
  version: 3.2.2
  nameNodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          dfsNamenodeNameDir: /stackable/hadoop/namenode/data
          ipcAddress:
            port: 9000
          httpAddress:
            port: 60000
          metricsPort: 50000
  dataNodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
        config:
          dfsDatanodeNameDir: /stackable/hadoop/datannode/data
          httpAddress:
            port: 61000
          metricsPort: 51000

