= Installation
:description: Install the Stackable HDFS operator and dependencies using stackablectl or Helm. Follow steps for setup and verification in Kubernetes.
:kind: https://kind.sigs.k8s.io/

Install the Stackable HDFS operator and its dependency, the Zookeeper operator, as well as the
commons, secret and listener operators which are required by all Stackable operators.

There are multiple ways to install the Stackable operators.
xref:management:stackablectl:index.adoc[] is the preferred way but Helm is also supported.
OpenShift users may prefer installing the operator from the RedHat Certified Operator catalog using the OpenShift web console.

[tabs]
====
stackablectl::
+
--
`stackablectl` is the command line tool to interact with Stackable operators and our recommended way to install
operators. Follow the xref:management:stackablectl:installation.adoc[installation steps] for your platform.

After you have installed `stackablectl`, run the following command to install all operators necessary for the HDFS cluster:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-operators]
----

The tool prints

[source]
include::example$getting_started/install_output.txt[]

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`.
For example, you can use the `--cluster kind` flag to create a Kubernetes cluster with {kind}[kind].
--

Helm::
+
--
You can also use Helm to install the operators. Add the Stackable Helm repository:
[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-add-repo]
----

Then install the Stackable Operators:
[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-install-operators]
----

Helm deploys the operators in a Kubernetes Deployment and apply the CRDs for the HDFS cluster (as well as the CRDs for the required operators).
--
====

== What's next

xref:getting_started/first_steps.adoc[Set up an HDFS cluster] and its dependencies and
xref:getting_started/first_steps.adoc#_verify_that_it_works[verify that it works].
